// Catalogo da vitrine FTW. Medidas de referencia, medidas da foto do produto, nao de fabricacao.
window.FTW_PRODUTOS = [
 { id:'whey',      cat:'Proteína',        nome:'Whey Ultra Protein 900 g',    med:'11,8 × 20,6 cm',
   desc:'15 g de proteína e 7,6 g de EAAs por porção. O pote de entrada do canal alimentar.' },
 { id:'creatina',  cat:'Creatina',        nome:'Creatina Monohidratada 300 g', med:'9,5 × 11,4 cm',
   desc:'100% pura e micronizada, sabor neutro. A categoria que mais puxa recompra.' },
 { id:'preworkout',cat:'Pré-treino',      nome:'Diabo Verde Pré-Workout 300 g', med:'9,5 × 11,4 cm',
   desc:'Beta-alanina, arginina, tirosina, cafeína e taurina. Linha Diabo Verde.' },
 { id:'delicious', cat:'Linha Delicious', nome:'Delicious Coffee 300 g',       med:'9,5 × 11,8 cm',
   desc:'A linha de sabor da FTW, feita para quem compra por prazer e não só por treino.' },
 { id:'wheynerd',  cat:'Collab',          nome:'Nerd Coffee Super Café 300 g', med:'9,5 × 11,8 cm',
   desc:'Collab Whey Nerd. Mostra como a marca usa parceria para abrir público novo.' },
 { id:'bcaa',      cat:'Aminoácidos',     nome:'BCAA 10:1:1 300 g',            med:'9,5 × 11,4 cm',
   desc:'Sabor limão. Aminoácido de giro rápido no balcão da farmácia.' },
 { id:'glutamina', cat:'Aminoácidos',     nome:'Glutamina Isolada 300 g',      med:'9,5 × 11,4 cm',
   desc:'Micronizada e isolada, 100% pura. Item de recompra da base fiel.' },
 { id:'thermo',    cat:'Termogênico',     nome:'Diabo Verde Thermo Dry 300 g', med:'9,5 × 11,4 cm',
   desc:'Sabor abacaxi. Sazonalidade forte de verão, pede plano de calendário.' },
 { id:'multivit',  cat:'Vitaminas',       nome:'Multi Vitaminas e Minerais',   med:'5,5 × 8,1 cm',
   desc:'60 cápsulas. Formato que cabe em pouco espaço: a peça certa para o balcão.' },
 { id:'joint',     cat:'Articulações',    nome:'Joint Move 90 cápsulas',       med:'5,8 × 11,7 cm',
   desc:'Ácido hialurônico e colágeno. Entrada no público de saúde, não só de treino.' },
 { id:'carnitina', cat:'Emagrecimento',   nome:'L-Carnitina 700 mg',           med:'5,8 × 11,7 cm',
   desc:'120 cápsulas. Categoria que conversa com farmácia e com loja especializada.' },
];
